stages:
  - build
  - test
  - checkstyle
  - deploy

build:
  stage: build
  image: maven:3.8.3-jdk-11
  script:
    - mvn clean package

test:
  stage: test
  image: maven:3.8.3-jdk-11
  script:
    - echo "Test DEMO app"
    - mvn test && mvn jacoco:report
    - cat target/site/jacoco/index.html | grep -o '.*'
  coverage: "/Total.*?([0-9]{1,3})%/"

checkstyle:
  stage: checkstyle
  image: maven:3.8.3-jdk-11
  script:
    - echo "Checkstyle DEMO app"
    - mvn checkstyle:check

variables:
  DB_IP: ec2-54-74-60-70.eu-west-1.compute.amazonaws.com
  DB_PORT: 5432
  DB_USER: dvuisidxtsghbd
  DB_PASSWORD: d4718329d17128e9c32d1c082dedefb6617190c9a87b812a8728bd548f49d388
  DB_DBNAME: d11ljba3hvvpk6

deploy:
  stage: deploy
  image: ruby:3.0
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=ds2021-energy-daniel-backend --api-key=$HEROKU_API_KEY
  only:
    - production
