stages:
  - build
  - test
  - checkstyle

build:
  stage: build
  image: maven:3.8.3-jdk-11
  script:
    - mvn clean package

test:
  stage: test
  image: maven:3.8.3-jdk-11
  script:
    - echo "Test DEMO app"
    - mvn test && mvn jacoco:report
    - cat target/site/jacoco/index.html | grep -o '.*'
  coverage: "/Total.*?([0-9]{1,3})%/"

checkstyle:
  stage: checkstyle
  image: maven:3.8.3-jdk-11
  script:
    - echo "Checkstyle DEMO app"
    - mvn checkstyle:check

variables:
  DB_IP: ec2-54-155-92-75.eu-west-1.compute.amazonaws.com
  DB_PORT: 5432
  DB_USER: vgwylexqedvnkq
  DB_PASSWORD: 4af77f70e75ca37095152f985fb98c002e03c11ee26f989e98da7ab70deb11ab
  DB_DBNAME: d40feluh83kpf4

deploy:
  stage: deploy
  image: ruby:2.4
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=ds2021-energy-daniel-backend --api-key=$HEROKU_API_KEY
  only:
    - production
