stages:
  - build
  - test
  - checkstyle

build:
  stage: build
  image: maven:3.8.3-jdk-11
  script:
    - mvn clean package

test:
  stage: test
  image: maven:3.8.3-jdk-11
  script:
    - echo "Test DEMO app"
    - mvn test && mvn jacoco:report
    - cat target/site/jacoco/index.html | grep -o '.*'
  coverage: "/Total.*?([0-9]{1,3})%/"

checkstyle:
  stage: checkstyle
  image: maven:3.8.3-jdk-11
  script:
    - echo "Checkstyle DEMO app"
    - mvn checkstyle:check